---

### 📄 docker-compose.yml
version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vector
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  ollama-models:
